### PR TITLE
Fake PR

### PR DESCRIPTION
**Pull request by jdvp**
Hey @JolleJolles, sorry to create this fake PR. The repo doesn't have issues but wanted to message you regarding your comment on my site. 

The one issue I am seeing right now is that the link you put in comment-post doesn't seem to be correct:
comment-post: https://docs.google.com/forms/d/e/1FAIpQLSe9F17myVLU52_B4UEdupm_Hfx5xXgTpVqgQyarNEQueNdM-A

when I try to navigate to that URL, I see this:
Screen Shot 2021-03-29 at 1 54 21 PM

### CODE REVIEW

**Comment by JolleJolles** [comment]
Thanks for your quick reply. I discovered that too, but noticed the url in your _config file actually does the same! So can't be that and I am sure the url is correct (at least with the stuff after the '/'). Any other ideas?

Also I will make sure to start an issue thread

**Comment by jdvp** [comment]
@JolleJolles looking at the source of the deployed page, I feel like maybe this is an issue with minification.
Screen Shot 2021-03-29 at 3 20 26 PM

It looks like the inline script has been all turned into a comment. Are you using a tool to minify the resulting page? If so, maybe try removing all of the comments from comment-section.html and see if that changes anything. I'm also trying to run locally but having ruby issues for now haha

**Comment by JolleJolles** [comment]
Thanks. I tried this and removed all commented text, but it is still not working unfortunately.. Could you maybe have another look? Appreciate it!

**Comment by JolleJolles** [comment]
I also tried if adding a comment in the google sheets shows it on the website and that doesn’t work either. I am sure the urls of the form and sheet are okay as well as the comment-post-fields "[entry.148489506, entry.1990599000, entry.1482663308]”. Would be great to get it working.. Can you think of any in-between step that could help test where the issue is, such as a way to test if the javascript is actually run? Cheers

**Comment by JolleJolles** [comment]
Thanks for helping out. I replaced the comment-section.html file and made the change with the locale but new comments are still not stored in the google sheet and any comments in the google sheet are not shown on the website.. I think the issue has to be with the javascript indeed. I tried looking at issues using js.do but I have no experience with JS at all. Maybe you could have a look? I also think there is some inconsisteny in the use of ‘ ` and “ that could potentially be an issue? Not sure. Note that I am using a theme (just-the-docs) that is likely calling the minify code. I don’t need it but don’t know how to turn it off either. 

Thanks for your persistence!

**Comment by jdvp** [comment]
@JolleJolles ok ok so it seems I added too many semicolons! We can see that by opening the inspect tool and looking at the console haha

Screen Shot 2021-03-30 at 11 41 53 AM

I've updated the file, please try with the latest version
https://drive.google.com/file/d/1uMetOEqojXAjkd92b6qkCPQbOnlaO_1P/view?usp=sharing

**Comment by JolleJolles** [comment]
Wonderful, now it ís working! Really nice. I would also like to add an email box, and will try to get it working, but let me know if you have already done this 😅 Also I will try and use your code to create a special comments page to function as a guestbook.

Thanks again for your great idea and help!

**Comment by jdvp** [comment]
@JolleJolles yes! great I am glad we got it working. I haven't added an email field yet but hopefully it wouldn't be too hard! If you end up doing it and get stuck, I can try to help haha

I'll update my article! it's nice actually getting some feedback that can lead to me improving it! Thanks and have a nice day!

**Pull request closed without merging**
